// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_api_2.Data;

#nullable disable

namespace web_api_2.Migrations
{
    [DbContext(typeof(PCsDbContext))]
    [Migration("20260525192213_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_api_2.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU/000111",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "Gaming processor",
                            Name = "Ryzen 7"
                        },
                        new
                        {
                            Code = "GPU/000222",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "gaming graphics card",
                            Name = "RTX 4090"
                        },
                        new
                        {
                            Code = "RAM/000333",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "DDR5 RAM module 16GB",
                            Name = "16GB"
                        });
                });

            modelBuilder.Entity("web_api_2.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1991, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "IN",
                            FoundationDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NV",
                            FoundationDate = new DateTime(1994, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nvidia"
                        });
                });

            modelBuilder.Entity("web_api_2.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Procesor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphic"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "SSD",
                            Name = "Disk"
                        });
                });

            modelBuilder.Entity("web_api_2.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Professional PC",
                            Stock = 5,
                            Warranty = 24,
                            Weight = 8.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Office PC",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Student PC",
                            Stock = 20,
                            Warranty = 12,
                            Weight = 6.0999999999999996
                        });
                });

            modelBuilder.Entity("web_api_2.Models.PcComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PcComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU/000111",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU/000222",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM/000333",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "CPU/000111",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM/000333",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("web_api_2.Models.Component", b =>
                {
                    b.HasOne("web_api_2.Models.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api_2.Models.ComponentType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("web_api_2.Models.PcComponent", b =>
                {
                    b.HasOne("web_api_2.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api_2.Models.Pc", "PC")
                        .WithMany("PcComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("web_api_2.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("web_api_2.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("web_api_2.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("web_api_2.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
